//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPUser()
        {
            this.TPBillRef = new HashSet<TPBillRef>();
            this.TPUserAddress = new HashSet<TPUserAddress>();
            this.TPUserCell = new HashSet<TPUserCell>();
        }
    
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public byte[] LastName { get; set; }
        public Nullable<int> Gender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPBillRef> TPBillRef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPUserAddress> TPUserAddress { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPUserCell> TPUserCell { get; set; }
    }
}
