//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillPayment
    {
        public string BillID { get; set; }
        public string SubjectID { get; set; }
        public string SubjectName { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<decimal> PaySum { get; set; }
        public Nullable<decimal> SumPaid { get; set; }
    }
}
