//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillItem
    {
        public string BillItemID { get; set; }
        public string BillID { get; set; }
        public string MenuID { get; set; }
        public string MenuName { get; set; }
        public string MenuUnitID { get; set; }
        public string MenuUnitName { get; set; }
        public string MenuTypeID { get; set; }
        public string MenuTypeName { get; set; }
        public string DepartID { get; set; }
        public string DepartName { get; set; }
        public string DepartTypeID { get; set; }
        public string DepartTypeName { get; set; }
        public Nullable<decimal> AmountOrder { get; set; }
        public Nullable<decimal> AmountOnTable { get; set; }
        public Nullable<decimal> AmountCancel { get; set; }
        public Nullable<decimal> MenuPrice { get; set; }
        public Nullable<decimal> MenuPrice2 { get; set; }
        public Nullable<decimal> SumOfConsume { get; set; }
        public Nullable<decimal> SumForDiscount { get; set; }
        public Nullable<decimal> SumOfService { get; set; }
        public Nullable<decimal> SumOfCookWay { get; set; }
        public string CookWayID { get; set; }
        public string CookWay { get; set; }
        public Nullable<decimal> CookWayPrice { get; set; }
        public string MenuPart { get; set; }
        public string Request { get; set; }
        public string TasteType { get; set; }
        public string CreatePersonID { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> ServingState { get; set; }
        public Nullable<bool> IsSentMenu { get; set; }
        public Nullable<bool> IsSent { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsSpecialPrice { get; set; }
        public Nullable<bool> IsDiscount { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<bool> IsPrinted { get; set; }
        public Nullable<System.DateTime> PrintTime { get; set; }
        public Nullable<bool> IsOnTable { get; set; }
        public Nullable<System.DateTime> OnTableTime { get; set; }
        public string MenuSetID { get; set; }
        public string MenuSetName { get; set; }
        public string MenuSetPrefix { get; set; }
        public string MenuSetItemID { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> TaxRate { get; set; }
        public Nullable<decimal> SumOfTax { get; set; }
    }
}
