//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JZZPEntities : DbContext
    {
        public JZZPEntities()
            : base("name=JZZPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TPBillRef> TPBillRefs { get; set; }
        public virtual DbSet<TPCallIn> TPCallIns { get; set; }
        public virtual DbSet<TPDeliver> TPDelivers { get; set; }
        public virtual DbSet<TPDriver> TPDrivers { get; set; }
        public virtual DbSet<TPPrintSetting> TPPrintSettings { get; set; }
        public virtual DbSet<TPUser> TPUsers { get; set; }
        public virtual DbSet<TPUserAddress> TPUserAddresses { get; set; }
        public virtual DbSet<TPUserCell> TPUserCells { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillItem> BillItems { get; set; }
        public virtual DbSet<TempBill> TempBills { get; set; }
        public virtual DbSet<TempBillItem> TempBillItems { get; set; }
        public virtual DbSet<BillPayment> BillPayments { get; set; }
    }
}
