//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JZZPEntities : DbContext
    {
        public JZZPEntities()
            : base("name=JZZPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TPDeliver> TPDelivers { get; set; }
        public virtual DbSet<TPDriver> TPDrivers { get; set; }
        public virtual DbSet<TPPrintSetting> TPPrintSettings { get; set; }
        public virtual DbSet<TPUser> TPUsers { get; set; }
        public virtual DbSet<TPUserAddress> TPUserAddresses { get; set; }
        public virtual DbSet<TPUserCell> TPUserCells { get; set; }
        public virtual DbSet<Bill> Bills { get; set; }
        public virtual DbSet<BillItem> BillItems { get; set; }
        public virtual DbSet<TempBill> TempBills { get; set; }
        public virtual DbSet<TempBillItem> TempBillItems { get; set; }
        public virtual DbSet<BillPayment> BillPayments { get; set; }
        public virtual DbSet<TPAddress> TPAddresses { get; set; }
        public virtual DbSet<TPCallIn> TPCallIns { get; set; }
        public virtual DbSet<TPBillRef> TPBillRefs { get; set; }
    }
}
