//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPAddress
    {
        public long AddressId { get; set; }
        public string HouseNumber { get; set; }
        public string AddressField1 { get; set; }
        public string AddressField2 { get; set; }
        public string AddressField3 { get; set; }
        public string TownCity { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> DeliveryMiles { get; set; }
    }
}
