//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPBillRef
    {
        public long BillRefId { get; set; }
        public Nullable<long> CallInId_FK { get; set; }
        public Nullable<System.Guid> UserId_FK { get; set; }
        public Nullable<long> AddressId_FK { get; set; }
        public string BillId_FK { get; set; }
        public Nullable<decimal> DeliverFeeOrigin { get; set; }
        public Nullable<decimal> DeliverMiles { get; set; }
        public Nullable<decimal> DeliverFee { get; set; }
        public int Status { get; set; }
        public Nullable<long> DeliverId_FK { get; set; }
        public bool ShowOnMain { get; set; }
    
        public virtual TPCallIn TPCallIn { get; set; }
        public virtual TPDeliver TPDeliver { get; set; }
        public virtual TPUser TPUser { get; set; }
        public virtual TPUserAddress TPUserAddress { get; set; }
    }
}
