//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPBillRef
    {
        public long BillRefId { get; set; }
        public Nullable<long> CallInId_FK { get; set; }
        public Nullable<System.Guid> UserId_FK { get; set; }
        public Nullable<long> AddressId_FK { get; set; }
        public string BillId_FK { get; set; }
        public Nullable<decimal> DeliverMiles { get; set; }
        public Nullable<decimal> DeliverFee { get; set; }
        public int Status { get; set; }
        public Nullable<long> DeliverId_FK { get; set; }
    
        public virtual TPCallIn TPCallIn { get; set; }
        public virtual TPDeliver TPDeliver { get; set; }
        public virtual TPUser TPUser { get; set; }
        public virtual TPUserAddress TPUserAddress { get; set; }
    }
}
