//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPDeliverItem
    {
        public long DeliverItemId { get; set; }
        public long DeliverId_FK { get; set; }
        public long BillRefId_FK { get; set; }
    
        public virtual TPBillRef TPBillRef { get; set; }
        public virtual TPDeliver TPDeliver { get; set; }
    }
}
