//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPDriver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPDriver()
        {
            this.TPDeliver = new HashSet<TPDeliver>();
        }
    
        public long DriverId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CellName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPDeliver> TPDeliver { get; set; }
    }
}
