//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPUserAddress
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TPUserAddress()
        {
            this.TPBillRef = new HashSet<TPBillRef>();
        }
    
        public long UserAddressId { get; set; }
        public System.Guid UserId_FK { get; set; }
        public string HouseNumber { get; set; }
        public string AddressField1 { get; set; }
        public string AddressField2 { get; set; }
        public string AddressField3 { get; set; }
        public string TownCity { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public Nullable<decimal> DeliveryMiles { get; set; }
    
        public virtual TPUser TPUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TPBillRef> TPBillRef { get; set; }
    }
}
