//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntitiesDABL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPUserCell
    {
        public long UserCellId { get; set; }
        public System.Guid UserId_FK { get; set; }
        public string CellNumber { get; set; }
    
        public virtual TPUser TPUser { get; set; }
    }
}
